In [23]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import MinMaxScaler, StandardScaler

from sklearn.svm import SVC
from sklearn.model_selection import train_test_split,GridSearchCV, RandomizedSearchCV

from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_csv('Social_Network_Ads.csv')
df

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [6]:
df['Gender'].replace({'Male' :1,'Female':0},inplace = True)

# Scaling

In [17]:
x = df.drop(['User ID','Purchased'],axis = 1)
y = df['Purchased']

std_scaler = StandardScaler()
x_scaled = std_scaler.fit_transform(x[['Age','EstimatedSalary']])
x = pd.DataFrame(x_scaled,columns = ['Age','EstimatedSalary'])
x['Gender'] = df['Gender']
x

Age  EstimatedSalary  Gender
0   -1.781797        -1.490046       1
1   -0.253587        -1.460681       1
2   -1.113206        -0.785290       0
3   -1.017692        -0.374182       0
4   -1.781797         0.183751       1
..        ...              ...     ...
395  0.797057        -0.844019       0
396  1.274623        -1.372587       1
397  1.179110        -1.460681       0
398 -0.158074        -1.078938       1
399  1.083596        -0.990844       0

[400 rows x 3 columns]

In [18]:

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=10, stratify=y)

# Model Training

In [19]:
svc_model = SVC()
svc_model.fit(x_train, y_train)

SVC()

# Evaluation

In [21]:
## Trainig Data Evaluation
y_pred_train = svc_model.predict(x_train)

cnf_matrix = confusion_matrix(y_train, y_pred_train)
print("Confusion Matrix :\n",cnf_matrix)

acc_score = accuracy_score(y_train, y_pred_train)
print("Accuracy Score is :",acc_score)

clf_report = classification_report(y_train, y_pred_train)
print("Classification Report :\n",clf_report)

Confusion Matrix :
 [[188  18]
 [ 11 103]]
Accuracy Score is : 0.909375
Classification Report :
               precision    recall  f1-score   support

           0       0.94      0.91      0.93       206
           1       0.85      0.90      0.88       114

    accuracy                           0.91       320
   macro avg       0.90      0.91      0.90       320
weighted avg       0.91      0.91      0.91       320



In [22]:
## Testing Data Evaluation
y_pred = svc_model.predict(x_test)

cnf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix :\n",cnf_matrix)

acc_score = accuracy_score(y_test, y_pred)
print("Accuracy Score is :",acc_score)

clf_report = classification_report(y_test, y_pred)
print("Classification Report :\n",clf_report)

Confusion Matrix :
 [[46  5]
 [ 2 27]]
Accuracy Score is : 0.9125
Classification Report :
               precision    recall  f1-score   support

           0       0.96      0.90      0.93        51
           1       0.84      0.93      0.89        29

    accuracy                           0.91        80
   macro avg       0.90      0.92      0.91        80
weighted avg       0.92      0.91      0.91        80



# Hyperparameter Tuning

In [29]:
svc_model = SVC()
hyp_grid = {'C':np.arange (1,50),
           "kernel" : ['linear', 'poly', 'rbf', 'sigmoid']}
cv = 5         
# rbf >> Radial Basis Function

gscv_model = GridSearchCV(svc_model,hyp_grid,cv = cv)
gscv_model.fit(x_train, y_train)

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]),
                         'kernel': ['linear', 'poly', 'rbf', 'sigmoid']})

In [25]:
gscv_model.best_estimator_

SVC(C=17)

In [26]:
## Trainig Data Evaluation
svc_model = SVC(C=17)
svc_model.fit(x_train, y_train)
y_pred_train = svc_model.predict(x_train)

cnf_matrix = confusion_matrix(y_train, y_pred_train)
print("Confusion Matrix :\n",cnf_matrix)

acc_score = accuracy_score(y_train, y_pred_train)
print("Accuracy Score is :",acc_score)

clf_report = classification_report(y_train, y_pred_train)
print("Classification Report :\n",clf_report)

Confusion Matrix :
 [[192  14]
 [  7 107]]
Accuracy Score is : 0.934375
Classification Report :
               precision    recall  f1-score   support

           0       0.96      0.93      0.95       206
           1       0.88      0.94      0.91       114

    accuracy                           0.93       320
   macro avg       0.92      0.94      0.93       320
weighted avg       0.94      0.93      0.93       320



In [27]:
## Testing Data Evaluation
y_pred = svc_model.predict(x_test)

cnf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix :\n",cnf_matrix)

acc_score = accuracy_score(y_test, y_pred)
print("Accuracy Score is :",acc_score)

clf_report = classification_report(y_test, y_pred)
print("Classification Report :\n",clf_report)

Confusion Matrix :
 [[45  6]
 [ 2 27]]
Accuracy Score is : 0.9
Classification Report :
               precision    recall  f1-score   support

           0       0.96      0.88      0.92        51
           1       0.82      0.93      0.87        29

    accuracy                           0.90        80
   macro avg       0.89      0.91      0.89        80
weighted avg       0.91      0.90      0.90        80

