# import libraries

In [1]:
import pandas as pd
import numpy as np

from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.preprocessing import MinMaxScaler,StandardScaler

import warnings
warnings.filterwarnings('ignore')

# 1.Problem statement

In [ ]:
To predict if patient is having heart disease or not

# 2.read the dataset

In [2]:
df = pd.read_csv('heart.csv')
df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

# 3.EDA

In [3]:
df.isna().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

# 4.train test split

In [5]:
x = df.drop('target',axis=1)
y = df['target']
y

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

In [6]:
xtrain,xtest,ytrain,ytest= train_test_split(x,y,test_size=0.25,random_state=35,stratify=y)

# 5. Model building

In [7]:
knn_model = KNeighborsClassifier()
knn_model.fit(xtrain,ytrain)

KNeighborsClassifier()

# 6. Model evaluation

In [8]:
# Testing data evaluation
ypredtest = knn_model.predict(xtest)

accuracy = accuracy_score(ytest,ypredtest)
print('Accuracy score :',accuracy)

confusionmatrix = confusion_matrix(ytest,ypredtest)
print('Confusion matrix :\n',confusionmatrix)

classificationreport = classification_report(ytest,ypredtest)
print('classification report :\n',classificationreport)

Accuracy score : 0.5657894736842105
Confusion matrix :
 [[16 19]
 [14 27]]
classification report :
               precision    recall  f1-score   support

           0       0.53      0.46      0.49        35
           1       0.59      0.66      0.62        41

    accuracy                           0.57        76
   macro avg       0.56      0.56      0.56        76
weighted avg       0.56      0.57      0.56        76



In [9]:
# Training data evaluation
ypredtrain = knn_model.predict(xtrain)

accuracy = accuracy_score(ytrain,ypredtrain)
print('Accuracy score :',accuracy)

confusionmatrix = confusion_matrix(ytrain,ypredtrain)
print('Confusion matrix :\n',confusionmatrix)

classificationreport = classification_report(ytrain,ypredtrain)
print('classification report :\n',classificationreport)

Accuracy score : 0.7533039647577092
Confusion matrix :
 [[ 71  32]
 [ 24 100]]
classification report :
               precision    recall  f1-score   support

           0       0.75      0.69      0.72       103
           1       0.76      0.81      0.78       124

    accuracy                           0.75       227
   macro avg       0.75      0.75      0.75       227
weighted avg       0.75      0.75      0.75       227



# Scaling

In [ ]:
1. without scaling and without hyperparameter tuning
2. Normalization and without hyperparameter tuning
3. Standardization and without hyperparameter tuning

4. without scaling and hyperparameter tuning
5. Normalization and hyperparameter tuning
6. Standardization and hyperparameter tuning

# 2.Normalization and without hyperparameter tuning

In [10]:
df = pd.read_csv('heart.csv')
df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [11]:
x = df.drop('target',axis=1)
y = df['target']
y

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

In [ ]:
fit >> calculation(xmin,xmax)
transform >> Apply this calculation to dataset

In [19]:
normal_scaler = MinMaxScaler()
array1 = normal_scaler.fit_transform(x)
df_normal = pd.DataFrame(array1,columns = x.columns)
df_normal

age  sex        cp  trestbps      chol  fbs  restecg   thalach  \
0    0.708333  1.0  1.000000  0.481132  0.244292  1.0      0.0  0.603053   
1    0.166667  1.0  0.666667  0.339623  0.283105  0.0      0.5  0.885496   
2    0.250000  0.0  0.333333  0.339623  0.178082  0.0      0.0  0.770992   
3    0.562500  1.0  0.333333  0.245283  0.251142  0.0      0.5  0.816794   
4    0.583333  0.0  0.000000  0.245283  0.520548  0.0      0.5  0.702290   
..        ...  ...       ...       ...       ...  ...      ...       ...   
298  0.583333  0.0  0.000000  0.433962  0.262557  0.0      0.5  0.396947   
299  0.333333  1.0  1.000000  0.150943  0.315068  0.0      0.5  0.465649   
300  0.812500  1.0  0.000000  0.471698  0.152968  1.0      0.5  0.534351   
301  0.583333  1.0  0.000000  0.339623  0.011416  0.0      0.5  0.335878   
302  0.583333  0.0  0.333333  0.339623  0.251142  0.0      0.0  0.786260   

     exang   oldpeak  slope    ca      thal  
0      0.0  0.370968    0.0  0.00  0.333333  
1      0.0  0.564516    0.0  0.00  0.666667  
2      0.0  0.225806    1.0  0.00  0.666667  
3      0.0  0.129032    1.0  0.00  0.666667  
4      1.0  0.096774    1.0  0.00  0.666667  
..     ...       ...    ...   ...       ...  
298    1.0  0.032258    0.5  0.00  1.000000  
299    0.0  0.193548    0.5  0.00  1.000000  
300    0.0  0.548387    0.5  0.50  1.000000  
301    1.0  0.193548    0.5  0.25  1.000000  
302    0.0  0.000000    0.5  0.25  0.666667  

[303 rows x 13 columns]

In [20]:
xtrain,xtest,ytrain,ytest= train_test_split(df_normal,y,test_size=0.25,random_state=35,stratify=y)

In [21]:
knn_model = KNeighborsClassifier()
knn_model.fit(xtrain,ytrain)

KNeighborsClassifier()

In [22]:
# Testing data evaluation
ypredtest = knn_model.predict(xtest)

accuracy = accuracy_score(ytest,ypredtest)
print('Accuracy score :',accuracy)

confusionmatrix = confusion_matrix(ytest,ypredtest)
print('Confusion matrix :\n',confusionmatrix)

classificationreport = classification_report(ytest,ypredtest)
print('classification report :\n',classificationreport)

Accuracy score : 0.7236842105263158
Confusion matrix :
 [[22 13]
 [ 8 33]]
classification report :
               precision    recall  f1-score   support

           0       0.73      0.63      0.68        35
           1       0.72      0.80      0.76        41

    accuracy                           0.72        76
   macro avg       0.73      0.72      0.72        76
weighted avg       0.72      0.72      0.72        76



In [23]:
# Training data evaluation
ypredtrain = knn_model.predict(xtrain)

accuracy = accuracy_score(ytrain,ypredtrain)
print('Accuracy score :',accuracy)

confusionmatrix = confusion_matrix(ytrain,ypredtrain)
print('Confusion matrix :\n',confusionmatrix)

classificationreport = classification_report(ytrain,ypredtrain)
print('classification report :\n',classificationreport)

Accuracy score : 0.8766519823788547
Confusion matrix :
 [[ 83  20]
 [  8 116]]
classification report :
               precision    recall  f1-score   support

           0       0.91      0.81      0.86       103
           1       0.85      0.94      0.89       124

    accuracy                           0.88       227
   macro avg       0.88      0.87      0.87       227
weighted avg       0.88      0.88      0.88       227



# 3. Standardization and without hyperparameter tuning

In [24]:
df = pd.read_csv('heart.csv')
df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [25]:
x = df.drop('target',axis=1)
y = df['target']
y

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

In [26]:
std_scaler = StandardScaler()
array1 = std_scaler.fit_transform(x)
df_std = pd.DataFrame(array1,columns = x.columns)
df_std

age       sex        cp  trestbps      chol       fbs   restecg  \
0    0.952197  0.681005  1.973123  0.763956 -0.256334  2.394438 -1.005832   
1   -1.915313  0.681005  1.002577 -0.092738  0.072199 -0.417635  0.898962   
2   -1.474158 -1.468418  0.032031 -0.092738 -0.816773 -0.417635 -1.005832   
3    0.180175  0.681005  0.032031 -0.663867 -0.198357 -0.417635  0.898962   
4    0.290464 -1.468418 -0.938515 -0.663867  2.082050 -0.417635  0.898962   
..        ...       ...       ...       ...       ...       ...       ...   
298  0.290464 -1.468418 -0.938515  0.478391 -0.101730 -0.417635  0.898962   
299 -1.033002  0.681005  1.973123 -1.234996  0.342756 -0.417635  0.898962   
300  1.503641  0.681005 -0.938515  0.706843 -1.029353  2.394438  0.898962   
301  0.290464  0.681005 -0.938515 -0.092738 -2.227533 -0.417635  0.898962   
302  0.290464 -1.468418  0.032031 -0.092738 -0.198357 -0.417635 -1.005832   

      thalach     exang   oldpeak     slope        ca      thal  
0    0.015443 -0.696631  1.087338 -2.274579 -0.714429 -2.148873  
1    1.633471 -0.696631  2.122573 -2.274579 -0.714429 -0.512922  
2    0.977514 -0.696631  0.310912  0.976352 -0.714429 -0.512922  
3    1.239897 -0.696631 -0.206705  0.976352 -0.714429 -0.512922  
4    0.583939  1.435481 -0.379244  0.976352 -0.714429 -0.512922  
..        ...       ...       ...       ...       ...       ...  
298 -1.165281  1.435481 -0.724323 -0.649113 -0.714429  1.123029  
299 -0.771706 -0.696631  0.138373 -0.649113 -0.714429  1.123029  
300 -0.378132 -0.696631  2.036303 -0.649113  1.244593  1.123029  
301 -1.515125  1.435481  0.138373 -0.649113  0.265082  1.123029  
302  1.064975 -0.696631 -0.896862 -0.649113  0.265082 -0.512922  

[303 rows x 13 columns]

In [27]:
xtrain,xtest,ytrain,ytest= train_test_split(df_std,y,test_size=0.25,random_state=35,stratify=y)

In [28]:
knn_model = KNeighborsClassifier()
knn_model.fit(xtrain,ytrain)

KNeighborsClassifier()

In [29]:
# Testing data evaluation
ypredtest = knn_model.predict(xtest)

accuracy = accuracy_score(ytest,ypredtest)
print('Accuracy score :',accuracy)

confusionmatrix = confusion_matrix(ytest,ypredtest)
print('Confusion matrix :\n',confusionmatrix)

classificationreport = classification_report(ytest,ypredtest)
print('classification report :\n',classificationreport)

Accuracy score : 0.8552631578947368
Confusion matrix :
 [[27  8]
 [ 3 38]]
classification report :
               precision    recall  f1-score   support

           0       0.90      0.77      0.83        35
           1       0.83      0.93      0.87        41

    accuracy                           0.86        76
   macro avg       0.86      0.85      0.85        76
weighted avg       0.86      0.86      0.85        76



In [30]:
# Training data evaluation
ypredtrain = knn_model.predict(xtrain)

accuracy = accuracy_score(ytrain,ypredtrain)
print('Accuracy score :',accuracy)

confusionmatrix = confusion_matrix(ytrain,ypredtrain)
print('Confusion matrix :\n',confusionmatrix)

classificationreport = classification_report(ytrain,ypredtrain)
print('classification report :\n',classificationreport)

Accuracy score : 0.8766519823788547
Confusion matrix :
 [[ 86  17]
 [ 11 113]]
classification report :
               precision    recall  f1-score   support

           0       0.89      0.83      0.86       103
           1       0.87      0.91      0.89       124

    accuracy                           0.88       227
   macro avg       0.88      0.87      0.87       227
weighted avg       0.88      0.88      0.88       227



# 4. without scaling and hyperparameter tuning

In [57]:
df = pd.read_csv('heart.csv')
df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [58]:
x = df.drop('target',axis=1)
y = df['target']
y

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

In [59]:
xtrain,xtest,ytrain,ytest= train_test_split(x,y,test_size=0.25,random_state=35,stratify=y)

In [60]:
knn_model = KNeighborsClassifier()
# knn_model.fit(xtrain,ytrain)

In [61]:
hyp = {'p' :[1,2],
      'n_neighbors' : np.arange(3,30)}

gscv_knn_model = GridSearchCV(knn_model,hyp,cv=5)

gscv_knn_model.fit(xtrain,ytrain)

gscv_knn_model.best_estimator_

KNeighborsClassifier(n_neighbors=7, p=1)

In [37]:
knn_model = gscv_knn_model.best_estimator_    # KNeighborsClassifier(n_neighbors=7, p=1)   
knn_model.fit(xtrain,ytrain)

KNeighborsClassifier(n_neighbors=7, p=1)

In [38]:
# Testing data evaluation
ypredtest = knn_model.predict(xtest)

accuracy = accuracy_score(ytest,ypredtest)
print('Accuracy score :',accuracy)

confusionmatrix = confusion_matrix(ytest,ypredtest)
print('Confusion matrix :\n',confusionmatrix)

classificationreport = classification_report(ytest,ypredtest)
print('classification report :\n',classificationreport)

Accuracy score : 0.6842105263157895
Confusion matrix :
 [[20 15]
 [ 9 32]]
classification report :
               precision    recall  f1-score   support

           0       0.69      0.57      0.62        35
           1       0.68      0.78      0.73        41

    accuracy                           0.68        76
   macro avg       0.69      0.68      0.68        76
weighted avg       0.68      0.68      0.68        76



In [39]:
# Training data evaluation
ypredtrain = knn_model.predict(xtrain)

accuracy = accuracy_score(ytrain,ypredtrain)
print('Accuracy score :',accuracy)

confusionmatrix = confusion_matrix(ytrain,ypredtrain)
print('Confusion matrix :\n',confusionmatrix)

classificationreport = classification_report(ytrain,ypredtrain)
print('classification report :\n',classificationreport)

Accuracy score : 0.788546255506608
Confusion matrix :
 [[ 72  31]
 [ 17 107]]
classification report :
               precision    recall  f1-score   support

           0       0.81      0.70      0.75       103
           1       0.78      0.86      0.82       124

    accuracy                           0.79       227
   macro avg       0.79      0.78      0.78       227
weighted avg       0.79      0.79      0.79       227



# 5. Normalization and hyperparameter tuning

In [40]:
df = pd.read_csv('heart.csv')
df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [41]:
x = df.drop('target',axis=1)
y = df['target']
y

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

In [42]:
normal_scaler = MinMaxScaler()
array1 = normal_scaler.fit_transform(x)
df_normal = pd.DataFrame(array1,columns = x.columns)
df_normal

age  sex        cp  trestbps      chol  fbs  restecg   thalach  \
0    0.708333  1.0  1.000000  0.481132  0.244292  1.0      0.0  0.603053   
1    0.166667  1.0  0.666667  0.339623  0.283105  0.0      0.5  0.885496   
2    0.250000  0.0  0.333333  0.339623  0.178082  0.0      0.0  0.770992   
3    0.562500  1.0  0.333333  0.245283  0.251142  0.0      0.5  0.816794   
4    0.583333  0.0  0.000000  0.245283  0.520548  0.0      0.5  0.702290   
..        ...  ...       ...       ...       ...  ...      ...       ...   
298  0.583333  0.0  0.000000  0.433962  0.262557  0.0      0.5  0.396947   
299  0.333333  1.0  1.000000  0.150943  0.315068  0.0      0.5  0.465649   
300  0.812500  1.0  0.000000  0.471698  0.152968  1.0      0.5  0.534351   
301  0.583333  1.0  0.000000  0.339623  0.011416  0.0      0.5  0.335878   
302  0.583333  0.0  0.333333  0.339623  0.251142  0.0      0.0  0.786260   

     exang   oldpeak  slope    ca      thal  
0      0.0  0.370968    0.0  0.00  0.333333  
1      0.0  0.564516    0.0  0.00  0.666667  
2      0.0  0.225806    1.0  0.00  0.666667  
3      0.0  0.129032    1.0  0.00  0.666667  
4      1.0  0.096774    1.0  0.00  0.666667  
..     ...       ...    ...   ...       ...  
298    1.0  0.032258    0.5  0.00  1.000000  
299    0.0  0.193548    0.5  0.00  1.000000  
300    0.0  0.548387    0.5  0.50  1.000000  
301    1.0  0.193548    0.5  0.25  1.000000  
302    0.0  0.000000    0.5  0.25  0.666667  

[303 rows x 13 columns]

In [43]:
xtrain,xtest,ytrain,ytest= train_test_split(df_normal,y,test_size=0.25,random_state=35,stratify=y)

In [44]:
hyp = {'p' :[1,2],
      'n_neighbors' : np.arange(3,30)}

gscv_knn_model = GridSearchCV(knn_model,hyp,cv=5)

gscv_knn_model.fit(xtrain,ytrain)

gscv_knn_model.best_estimator_

KNeighborsClassifier(n_neighbors=7, p=1)

In [45]:
knn_model = KNeighborsClassifier(n_neighbors=7, p=1)
knn_model.fit(xtrain,ytrain)

KNeighborsClassifier(n_neighbors=7, p=1)

In [46]:
# Testing data evaluation
ypredtest = knn_model.predict(xtest)

accuracy = accuracy_score(ytest,ypredtest)
print('Accuracy score :',accuracy)

confusionmatrix = confusion_matrix(ytest,ypredtest)
print('Confusion matrix :\n',confusionmatrix)

classificationreport = classification_report(ytest,ypredtest)
print('classification report :\n',classificationreport)

Accuracy score : 0.7894736842105263
Confusion matrix :
 [[27  8]
 [ 8 33]]
classification report :
               precision    recall  f1-score   support

           0       0.77      0.77      0.77        35
           1       0.80      0.80      0.80        41

    accuracy                           0.79        76
   macro avg       0.79      0.79      0.79        76
weighted avg       0.79      0.79      0.79        76



In [47]:
# Training data evaluation
ypredtrain = knn_model.predict(xtrain)

accuracy = accuracy_score(ytrain,ypredtrain)
print('Accuracy score :',accuracy)

confusionmatrix = confusion_matrix(ytrain,ypredtrain)
print('Confusion matrix :\n',confusionmatrix)

classificationreport = classification_report(ytrain,ypredtrain)
print('classification report :\n',classificationreport)

Accuracy score : 0.8722466960352423
Confusion matrix :
 [[ 82  21]
 [  8 116]]
classification report :
               precision    recall  f1-score   support

           0       0.91      0.80      0.85       103
           1       0.85      0.94      0.89       124

    accuracy                           0.87       227
   macro avg       0.88      0.87      0.87       227
weighted avg       0.88      0.87      0.87       227



# 6. Standardization and hyperparameter tuning

In [48]:
df = pd.read_csv('heart.csv')
df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [49]:
x  = df.drop('target',axis=1)
y = df['target']

In [50]:
std_scaler = StandardScaler()
array1 = std_scaler.fit_transform(x)
df_scaler = pd.DataFrame(array1,columns=x.columns)
df_scaler

age       sex        cp  trestbps      chol       fbs   restecg  \
0    0.952197  0.681005  1.973123  0.763956 -0.256334  2.394438 -1.005832   
1   -1.915313  0.681005  1.002577 -0.092738  0.072199 -0.417635  0.898962   
2   -1.474158 -1.468418  0.032031 -0.092738 -0.816773 -0.417635 -1.005832   
3    0.180175  0.681005  0.032031 -0.663867 -0.198357 -0.417635  0.898962   
4    0.290464 -1.468418 -0.938515 -0.663867  2.082050 -0.417635  0.898962   
..        ...       ...       ...       ...       ...       ...       ...   
298  0.290464 -1.468418 -0.938515  0.478391 -0.101730 -0.417635  0.898962   
299 -1.033002  0.681005  1.973123 -1.234996  0.342756 -0.417635  0.898962   
300  1.503641  0.681005 -0.938515  0.706843 -1.029353  2.394438  0.898962   
301  0.290464  0.681005 -0.938515 -0.092738 -2.227533 -0.417635  0.898962   
302  0.290464 -1.468418  0.032031 -0.092738 -0.198357 -0.417635 -1.005832   

      thalach     exang   oldpeak     slope        ca      thal  
0    0.015443 -0.696631  1.087338 -2.274579 -0.714429 -2.148873  
1    1.633471 -0.696631  2.122573 -2.274579 -0.714429 -0.512922  
2    0.977514 -0.696631  0.310912  0.976352 -0.714429 -0.512922  
3    1.239897 -0.696631 -0.206705  0.976352 -0.714429 -0.512922  
4    0.583939  1.435481 -0.379244  0.976352 -0.714429 -0.512922  
..        ...       ...       ...       ...       ...       ...  
298 -1.165281  1.435481 -0.724323 -0.649113 -0.714429  1.123029  
299 -0.771706 -0.696631  0.138373 -0.649113 -0.714429  1.123029  
300 -0.378132 -0.696631  2.036303 -0.649113  1.244593  1.123029  
301 -1.515125  1.435481  0.138373 -0.649113  0.265082  1.123029  
302  1.064975 -0.696631 -0.896862 -0.649113  0.265082 -0.512922  

[303 rows x 13 columns]

In [51]:
xtrain,xtest,ytrain,ytest = train_test_split(df_scaler,y,test_size=0.25,random_state=35,stratify=y)
xtrain

age       sex        cp  trestbps      chol       fbs   restecg  \
298  0.290464 -1.468418 -0.938515  0.478391 -0.101730 -0.417635  0.898962   
196 -0.922713  0.681005  1.002577  1.049520 -0.294985 -0.417635  0.898962   
193  0.621330  0.681005 -0.938515  0.763956  0.690615 -0.417635 -1.005832   
149 -1.363869  0.681005  1.002577 -0.092738 -1.280584 -0.417635  0.898962   
58  -2.246179  0.681005  1.973123 -0.778093 -1.241933 -0.417635 -1.005832   
..        ...       ...       ...       ...       ...       ...       ...   
146 -1.143291 -1.468418  1.002577 -0.778093 -0.082404 -0.417635  0.898962   
17   1.283063 -1.468418  1.973123  1.049520 -0.391612 -0.417635  0.898962   
140 -0.371269 -1.468418  1.002577 -0.663867  0.941846 -0.417635 -1.005832   
94  -1.033002 -1.468418  0.032031 -1.120770 -1.667094 -0.417635  0.898962   
97  -0.260980  0.681005 -0.938515 -1.349222 -0.256334  2.394438  0.898962   

      thalach     exang   oldpeak     slope        ca      thal  
298 -1.165281  1.435481 -0.724323 -0.649113 -0.714429  1.123029  
196 -0.115749 -0.696631  2.208842 -0.649113 -0.714429 -0.512922  
193 -0.334401  1.435481  1.518686 -0.649113  1.244593  1.123029  
149  0.015443 -0.696631 -0.896862  0.976352 -0.714429 -0.512922  
58   1.064975 -0.696631 -0.896862  0.976352 -0.714429 -0.512922  
..        ...       ...       ...       ...       ...       ...  
146 -0.028288 -0.696631 -0.638053 -0.649113  0.265082 -0.512922  
17  -1.558855 -0.696631  1.346147 -2.274579 -0.714429 -0.512922  
140  0.321556 -0.696631 -0.379244  0.976352 -0.714429 -0.512922  
94  -0.509323 -0.696631 -0.896862 -0.649113 -0.714429 -0.512922  
97  -0.115749 -0.696631 -0.810592  0.976352  2.224104  1.123029  

[227 rows x 13 columns]

In [53]:
knn_model = KNeighborsClassifier()

hyp  = {'p':[1,2],'n_neighbors':np.arange(3,30)}

gscv_knn_model = GridSearchCV(knn_model,hyp,cv=5)

gscv_knn_model.fit(xtrain,ytrain)

gscv_knn_model.best_estimator_

KNeighborsClassifier(n_neighbors=13)

In [54]:
knn_model = KNeighborsClassifier(n_neighbors=13)
knn_model.fit(xtrain,ytrain)

KNeighborsClassifier(n_neighbors=13)

In [55]:
# Testing data evaluation
ypredtest = knn_model.predict(xtest)

accuracy = accuracy_score(ytest,ypredtest)
print('Accuracy score :',accuracy)

confusionmatrix = confusion_matrix(ytest,ypredtest)
print('Confusion matrix :\n',confusionmatrix)

classificationreport = classification_report(ytest,ypredtest)
print('classification report :\n',classificationreport)

Accuracy score : 0.8421052631578947
Confusion matrix :
 [[27  8]
 [ 4 37]]
classification report :
               precision    recall  f1-score   support

           0       0.87      0.77      0.82        35
           1       0.82      0.90      0.86        41

    accuracy                           0.84        76
   macro avg       0.85      0.84      0.84        76
weighted avg       0.84      0.84      0.84        76



In [56]:
# Training data evaluation
ypredtrain = knn_model.predict(xtrain)

accuracy = accuracy_score(ytrain,ypredtrain)
print('Accuracy score :',accuracy)

confusionmatrix = confusion_matrix(ytrain,ypredtrain)
print('Confusion matrix :\n',confusionmatrix)

classificationreport = classification_report(ytrain,ypredtrain)
print('classification report :\n',classificationreport)

Accuracy score : 0.8546255506607929
Confusion matrix :
 [[ 78  25]
 [  8 116]]
classification report :
               precision    recall  f1-score   support

           0       0.91      0.76      0.83       103
           1       0.82      0.94      0.88       124

    accuracy                           0.85       227
   macro avg       0.86      0.85      0.85       227
weighted avg       0.86      0.85      0.85       227

